### ISSUE TITLE
(LOW) showing fluorescence in a popup window

### ISSUE THREAD

**Issue by nathanbollig** [DOI-USGS/rt-quic-db#44] opened 2020-12-24 05:18 UTC
DESCRIPTION
select options to see all wells fluorescence image grid, then click on a particular image (say A03) then it should open in a pop-up window.

SESSION VARIABLES (The user elected to submit this information with their request.)
email: cmohatny2@wisc.edu
first_name: Chit
last_name: test
loc_ID: 118
name: Chit
role: default
temp_password_flag: False
user_ID: 32
username: chitTest

**Comment by nbollig-usgs** [comment] 2023-03-02 18:07
Duplicate of #21. Closing.

**Closed by nbollig-usgs** 2023-03-02 18:07 UTC
Labels: enhancement, UI enhancement
